[package]
name = "nosv"
version = "1.0.0"
edition = "2024"
rust-version = "1.92"
license = "GPL-3.0-only"
description = "A safe Rust runtime and async executor for nOS-V"
readme = "README.md"

[dependencies]
libc = "0.2"
nosv-sys = "0.1.0"
uring = { package = "io-uring", git = "https://github.com/Orkking2/io-uring.git", rev = "928e28ae35fe16d652a6cc52de71add50297a32e", version = "0.7.13", optional = true }
socket2 = { version = "0.6", features = ["all"], optional = true }
tokio = { version = "1", default-features = false, features = ["io-util"], optional = true }
ubq = { version = "5", optional = true }

[features]
default = ["rt", "time", "io-uring"]
rt = []
time = ["rt"]
io-uring = ["rt", "dep:socket2", "dep:ubq", "dep:uring"]
tokio-compat = ["io-uring", "dep:tokio"]
futures-io = ["io-uring"]
native-sync = []

[dev-dependencies]
static_assertions = "1"
loom = "0.7"

[[example]]
name = "net_io_poc"
required-features = ["io-uring", "time"]

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
undocumented_unsafe_blocks = "deny"
